### ISSUE TITLE
Starstrike Blast missing cards

### ISSUE THREAD

**Issue by forsetite** [AlanOC91/YGOPRODeck#270] opened 2021-05-24 00:34 UTC
A lot of the Karakuri cards are missing in the set - both in the pack opener and collection manager. The card prices and scores also seem to be not working as intended in the pack opener.

I believe Force of the Breaker (e.g. Otherworld - The "A" Zone) and Chaos Impact (e.g. Seraphim Papillion) also has some missing cards, so it might be worth just double-checking those sets as well, but neither are as bad as Starstrike Blast.

**Comment by AlanOC91** [comment] 2021-05-24 11:26
I know what the issue is here and will work to fix it soon.

**Comment by AlanOC91** [comment] 2021-05-24 11:33
Just checked the price issue. It's a bit strange we don't have a market price for the Unlimited version of most of the cards from Starstrike Blast from TCGplayer. We get our prices directly from TCGplayer but I can see in the data they are missing prices for most of these Unlimited Starstrike Blast cards. Will investigate a bit more.

**Comment by AlanOC91** [comment] 2021-05-24 11:38
Well go figure, Starstrike Blast is the only core set that did not have an Unlimited edition print run. I don't know why we have some Unlimited edition prices for a couple of the cards from the TCGplayer data. Must be a mistake on their end. Because we had a handful of Unlimited edition prices my algorithm was choosing between 1st Edition/Unlimited for rarity of pack. 

I've changed Starstrike Blast to only ever be 1st Edition now.

**Comment by AlanOC91** [comment] 2021-05-24 11:42
Cards not showing up should also now be fixed in multiple sets.

**Closed by AlanOC91** 2021-05-24 11:42 UTC
Labels: api, bug
